export const emojis = [
    { title: 'grinning face', character: '😀' },
    { title: 'beaming face with smiling eyes', character: '😁' },
    { title: 'face with tears of joy', character: '😂' },
    { title: 'rolling on the floor laughing', character: '🤣' },
    { title: 'grinning face with big eyes', character: '😃' },
    { title: 'grinning face with smiling eyes', character: '😄' },
    { title: 'grinning face with sweat', character: '😅' },
    { title: 'grinning_squinting_face', character: "😆" },
    { title: 'winking face', character: '😉' },
    { title: 'smiling face with smiling eyes', character: '😊' },
    { title: 'face savoring food', character: '😋' },
    { title: 'smiling face with sunglasses', character: '😎' },
    { title: 'smiling face with heart-eyes', character: '😍' },
    { title: 'face blowing a kiss', character: '😘' },
    { title: 'kissing face', character: '😗' },
    { title: 'kissing face with smiling eyes', character: '😙' },
    { title: 'kissing face with closed eyes', character: '😚' },
    { title: 'slightly smiling face', character: '🙂' },
    { title: 'hugging', character: '🤗' },
    { title: 'star-struck', character: '🤩' },
    { title: 'thinking', character: '🤔' },
    { title: 'face with raised eyebrow', character: '🤨' },
    { title: 'neutral', character: '😐' },
    { title: 'expressionless', character: '😑' },
    { title: 'face without mouth', character: '😶' },
    { title: 'face with rolling eyes', character: '🙄' },
    { title: 'smirking face', character: '😏' },
    { title: 'persevering face', character: '😣' },
    { title: 'sad but relieved face', character: '😥' },
    { title: 'face with open mouth', character: '😮' },
    { title: 'zipper-mouth face', character: '🤐' },
    { title: 'hushed', character: '😯' },
    { title: 'sleepy face', character: '😪' },
    { title: 'tired', character: '😫' },
    { title: 'sleeping face', character: '😴' },
    { title: 'relieved_face', character: '😌' },
    { title: 'face with tongue', character: '😛' },
    { title: 'winking_face_with_tongue', character: '😜' },
    { title: 'squinting face with tongue', character: '😝' },
    { title: 'drooling', character: '🤤' },
    { title: 'unamused', character: '😒' },
    { title: 'downcast face with sweat', character: '😓' },
    { title: 'pensive', character: '' },
    { title: 'pensive', character: '😔' },
    { title: 'confused', character: '😕' },
    { title: 'upside-down', character: '🙃' },
    { title: 'money-mouth face', character: '🤑' },
    { title: 'astonished', character: '😲' },
    { title: 'slightly frowning face', character: '🙁' },
    { title: 'confounded', character: '😖' },
    { title: 'disappointed', character: '😞' },
    { title: 'worried', character: '😟' },
    { title: 'face with steam from nose', character: '😤' },
    { title: 'crying face', character: '😢' },
    { title: 'loudly crying face', character: '😭' },
    { title: 'frowning face with open mouth', character: '😦' },
    { title: 'anguished', character: '😧' },
    { title: 'fearful', character: '😨' },
    { title: 'weary', character: '😩' },
    { title: 'exploding head', character: '🤯' },
    { title: 'grimacing face', character: '😬' },
    { title: 'anxious face with sweat', character: '😰' },
    { title: 'face screaming in fear', character: '😱' },
    { title: 'flushed', character: '😳' },
    { title: 'zany face', character: '🤪' },
    { title: 'dizzy', character: '😵' },
    { title: 'pouting', character: '😡' },
    { title: 'angry', character: '😠' },
    { title: 'face with symbols on mouth', character: '🤬' },
    { title: 'face with medical mask', character: '😷' },
    { title: 'face with head-bandage', character: '🤒' },
    { title: 'nauseated', character: '🤢' },
    { title: 'face vomiting', character: '🤮' },    
    { title: 'sneezing face', character: '🤧' },
    { title: 'smiling face with halo', character: '😇' },
    { title: 'cowboy', character: '🤠' },
    { title: 'lying face', character: '🤥' },
    { title: 'shushing face', character: '🤫' },
    { title: 'face with hand over mouth', character: '🤭' },
    { title: 'face with monocle', character: '🧐' },
    { title: 'nerd', character: '🤓' },
    { title: 'smiling face with horns', character: '😈' },
    { title: 'angry face with horns', character: '👿' },
    { title: 'clown', character: '🤡' },    
    { title: 'ogre', character: '👹' },
    { title: 'goblin', character: '👺' },
    { title: 'skull', character: '💀' },
    { title: 'ghost', character: '👻' },
    { title: 'alien', character: '👽' },
    { title: 'alien monster', character: '👾' },
    { title: 'robot', character: '🤖' },
    { title: 'pile of poo', character: '💩' },
    { title: 'grinning cat face', character: '😺' },
    { title: 'grinning cat face with smiling eyes', character: '😸' },
    { title: 'cat face with tears of joy', character: '😹' },    
    { title: 'smiling cat face with heart-eyes', character: '😻' },
    { title: 'cat face with wry smile', character: '😼' },
    { title: 'kissing cat face', character: '😽' },
    { title: 'weary cat', character: '🙀' },
    { title: 'crying cat face', character: '😿' },
    { title: 'pouting cat', character: '😾' },
    { title: 'see-no-evil monkey', character: '🙈' },
    { title: 'hear-no-evil monkey', character: '🙉' },
    { title: 'speak-no-evil monkey', character: '🙊' }  
];
